services:
  frontend:
    build:
      context: frontend
      dockerfile: ../Dockerfile.frontend
    image: mohammadyehya/imc_interface-frontend:latest
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      aimodel_service:
        condition: service_started
    networks:
      - app_network
  aimodel_service:
    build:
      context: aimodel_service
      dockerfile: ../Dockerfile.aimodel_service
    image: mohammadyehya/imc_interface-aimodel_service:latest
    ports:
      - 8000:8000
    networks:
      - app_network
networks:
  app_network: