services:
  frontend:
    build:
      context: frontend
      dockerfile: ../Dockerfile.frontend
    image: mohammadyehya/imc_interface-frontend:latest
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_started
    networks:
      - app_network
  backend:
    build:
      context: backend
      dockerfile: ../Dockerfile.backend
    image: mohammadyehya/imc_interface-backend:latest
    ports:
      - 8000:8000
    networks:
      - app_network
networks:
  app_network: