ARG PYTHON_VERSION=3.13.1
FROM python:${PYTHON_VERSION}-slim as base

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["fastapi", "run", "main.py"]