ARG PYTHON_VERSION=3.13.1
FROM python:${PYTHON_VERSION}-slim as base

WORKDIR /app


COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

RUN python -c "from transformers import ViTForImageClassification; model = ViTForImageClassification.from_pretrained('google/vit-base-patch16-224-in21k', num_labels=2)"

EXPOSE 8000

CMD ["fastapi", "run", "main.py"]
